In [1]:
print("ApplyPilot AI")
print("TinyFish Job & Internship Finder")
print("Project setup started successfully!")

ApplyPilot AI
TinyFish Job & Internship Finder
Project setup started successfully!

In [2]:
%pip install -q requests

In [4]:
from google.colab import userdata

API_KEY = userdata.get("TINYFISH_API_KEY")

if API_KEY:
    print("API key loaded successfully!")
else:
    print("API key missing. Check Colab Secrets.")

API key loaded successfully!

In [5]:
import requests
from IPython.display import display, Markdown

url = "https://api.search.tinyfish.ai"

params = {
    "query": "AI machine learning internships for students in India",
    "location": "IN",
    "language": "en"
}

headers = {
    "X-API-Key": API_KEY
}

response = requests.get(
    url,
    params=params,
    headers=headers,
    timeout=60
)

print("Status code:", response.status_code)

if response.ok:
    data = response.json()
    results = data.get("results", [])

    print("Results found:", len(results))

    for i, job in enumerate(results, start=1):
        print(f"\n{i}. {job.get('title', 'No title')}")
        print("Website:", job.get("site_name", "Unknown"))
        print("URL:", job.get("url", "No URL"))
        print("Details:", job.get("snippet", "No description"))
else:
    print("Request failed:", response.text[:1000])

Status code: 200
Results found: 9

1. Work with us - Apple Machine Learning Research
Website: machinelearning.apple.com
URL: https://machinelearning.apple.com/work-with-us
Details: Explore full-time opportunities Internships in Machine Learning and AI Get hands-on machine learning experience with our researchers. Come to Apple as a  ...

2. Machine Learning Internships - 151 Intern Jobs in Oct 2026
Website: internshala.com
URL: https://internshala.com/internships/machine-learning-internship/
Details: Currently, there are 151 active Machine Learning internship vacancies from 130 companies across key sector(s) such as IT/Technology, Education/Teaching/ ...

3. 507 Artificial Intelligence Intern jobs in India
Website: in.linkedin.com
URL: https://in.linkedin.com/jobs/artificial-intelligence-intern-jobs
Details: 507 Artificial Intelligence Intern Jobs in India · AI Prompt Engineer Internship in Pune · Artificial Intelligence (AI) Internship in Mumbai · Intern - AI/ML. Read more

4. Internships in India for DA/DS/ML/AI Roles
Website: www.kaggle.com
URL: https://www.kaggle.com/getting-started/187186
Details: Here are some links through which you might be able to find Internships based on your interests · Data Science · Machine Learning / Artificial Intelligence /CV/NLP. Read more

5. 160 machine learning intern jobs in India, October 2026
Website: www.glassdoor.co.in
URL: https://www.glassdoor.co.in/Job/india-machine-learning-intern-jobs-SRCH_IL.0,5_IN115_KO6,29.htm
Details: AI /ML Intern ( Machine Learning & Generative AI ). India . ₹15,000 - ₹20,000 (Employer provided). Easy Apply. Assist in developing and implementing machine ... Read more

6. AI & ML Internship in India | Certificate Program
Website: clinilaunchresearch.in
URL: https://clinilaunchresearch.in/internship/ai-ml-internship/
Details: This 3-month AI ML Internship in India for freshers is designed to help learners understand how AI and machine learning are applied to real-world healthcare ... Read more

7. 100 Ai Ml Internship Job Vacancies
Website: in.indeed.com
URL: https://in.indeed.com/q-ai-ml-internship-jobs.html
Details: Indeed.com. This internship provides freshers and students with an opportunity to build practical AI/ML skills , work on real-world projects, Stipend:* ₹10,000 ...

8. Internship jobs | IBM Careers
Website: www.ibm.com
URL: https://www.ibm.com/in-en/careers/internships
Details: India Internship openings Research Advanced AI - MSC-PHD- Student Position- Research Lab Internship Multiple Cities Research Applied AI Research Intern - R&D  ...

9. 4 Machine Learning Engineering Internships in India
Website: unstop.com
URL: https://unstop.com/internship/machine-learning-engineering-internship
Details: AI/ML Internship . Skillorbit Private Limited. No prior experience required. Full Time. Hybrid | Bangalore. AI/ML Internship. Postgraduate. +3. 8 K - 20 K/Month ... Read more

In [6]:
import pandas as pd
from urllib.parse import urlsplit, urlunsplit

def clean_url(url):
    if not url:
        return ""
    parts = urlsplit(url)
    return urlunsplit((
        parts.scheme,
        parts.netloc.lower(),
        parts.path.rstrip("/"),
        "",
        ""
    ))

jobs = []
seen_urls = set()

for item in results:
    title = item.get("title", "").strip()
    url = item.get("url", "").strip()

    if not title or not url:
        continue

    normalized_url = clean_url(url)

    if normalized_url in seen_urls:
        continue

    seen_urls.add(normalized_url)

    jobs.append({
        "Title": title,
        "Company / Website": item.get("site_name", ""),
        "URL": url,
        "Description": item.get("snippet", "")
    })

jobs_df = pd.DataFrame(jobs)

print("Unique listings:", len(jobs_df))
display(jobs_df)

Unique listings: 9

,Title,Company / Website,URL,Description
0,Work with us - Apple Machine Learning Research,machinelearning.apple.com,https://machinelearning.apple.com/work-with-us,Explore full-time opportunities Internships in...
1,Machine Learning Internships - 151 Intern Jobs...,internshala.com,https://internshala.com/internships/machine-le...,"Currently, there are 151 active Machine Learni..."
2,507 Artificial Intelligence Intern jobs in India,in.linkedin.com,https://in.linkedin.com/jobs/artificial-intell...,507 Artificial Intelligence Intern Jobs in Ind...
3,Internships in India for DA/DS/ML/AI Roles,www.kaggle.com,https://www.kaggle.com/getting-started/187186,Here are some links through which you might be...
4,"160 machine learning intern jobs in India, Oct...",www.glassdoor.co.in,https://www.glassdoor.co.in/Job/india-machine-...,AI /ML Intern ( Machine Learning & Generative ...
5,AI & ML Internship in India | Certificate Program,clinilaunchresearch.in,https://clinilaunchresearch.in/internship/ai-m...,This 3-month AI ML Internship in India for fre...
6,100 Ai Ml Internship Job Vacancies,in.indeed.com,https://in.indeed.com/q-ai-ml-internship-jobs....,Indeed.com. This internship provides freshers ...
7,Internship jobs | IBM Careers,www.ibm.com,https://www.ibm.com/in-en/careers/internships,India Internship openings Research Advanced AI...
8,4 Machine Learning Engineering Internships in ...,unstop.com,https://unstop.com/internship/machine-learning...,AI/ML Internship . Skillorbit Private Limited....

In [7]:
%pip install -q tinyfish

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.8/42.8 kB 2.4 MB/s eta 0:00:00

In [8]:
import os
from tinyfish import TinyFish

# Configure the SDK with your existing API key
os.environ["TINYFISH_API_KEY"] = API_KEY
client = TinyFish()

# Select up to 5 distinct URLs from our search results
urls = jobs_df["URL"].dropna().drop_duplicates().head(5).tolist()

print("Fetching", len(urls), "pages...")

result = client.fetch.get_contents(
    urls=urls,
    format="markdown",
    ttl=0,
    purpose="Find genuine AI and machine learning internship openings, including role, location, requirements, and application links."
)

# Display successfully fetched pages
for page in result.results:
    print("\n" + "=" * 70)
    print("TITLE:", page.title)
    print("URL:", page.url)
    print("-" * 70)
    print(page.text[:2500])

# Display any individual URL failures
for error in result.errors:
    print("\nFAILED:", error.url)
    print("Reason:", error.error)

Fetching 5 pages...

======================================================================
TITLE: Work with us
URL: https://machinelearning.apple.com/work-with-us
----------------------------------------------------------------------
# Let’s innovate together.

Build amazing machine learning experiences with Apple. Discover opportunities for developers and researchers at Apple.

## Jobs in Machine Learning and AI

Our machine learning research teams collaborate to deliver amazing experiences that improve the lives of millions of people every day.

Explore full-time opportunities

## Internships in Machine Learning and AI

Get hands-on machine learning experience with our researchers. Come to Apple as a student, and your team will welcome you as a full contributor.

Explore internship opportunities

## Apple Scholars in AIML

The PhD fellowships in Machine Learning and AI were created to celebrate the contributions of students pursuing cutting-edge fundamental and applied machine learning research worldwide.

Explore Scholars opportunities

### Manuel Burger

ETH Zurich

AI for Health and Wellness

### Matheus Correa Lindino

State University of Campinas (UNICAMP)

AI for Health and Wellness

### Zeyu Huang

University of Edinburgh

Information Retrieval and Knowledge

### Nirmit Joshi

Toyota Technological Institute at Chicago (TTIC)

ML Theory

### Jinuk Kim

Seoul National University

ML Algorithms and Architectures

### Ha Le

Northeastern University

Human Centered AI

### Ming Li

University of Maryland - College Park

Data-Centric AI

### Shufan Li

University of California - Los Angeles

ML Algorithms and Architectures

### Ephraim Linder

Boston University

Privacy Preserving Machine Learning

### Mahbod Majid

Massachusetts Institute of Technology

Privacy Preserving Machine Learning

### Jan Meyer Saragih

NAIST (NARA Institute of Science and Technology)

Speech and Natural Language

### Sruthi Sudhakar

Columbia University

Interactive ML and Agents

### Linwei Tao

University of Sydney

AI for Ethics and Fairness

### Fengrui Tian

University of Pennsylvania

Computer Vision

### Tobias Weinberg

Cornell University

AI for Accessibility

### Kyra Wilson

University of Washington

AI for Ethics and Fairness

### Xindi (Cindy) Wu

Princeton University

Data-Centric AI

### Jianglong Ye

University of California - San Diego

Interactive ML and Agents

### Jingyang Yuan

Peking University

Speech and Natural Language

### Maike Züfle

Karlsruhe Institute of Technology (KIT)

Speech and Natural Language

## AIML Residency Program

The AIML Residency Program invites experts in various fields to apply their own domain expertise to innovate and build revolutionary machine learning

======================================================================
TITLE: Machine Learning Internships - 144 Intern Jobs in Oct 2026
URL: https://internshala.com/internships/machine-learning-internship/
----------------------------------------------------------------------
## Machine Learning Internship Snapshot

Looking for Machine Learning internships? Currently, there are 144 active Machine Learning internship vacancies from 130 companies across key sector(s) such as IT/Technology, Education/Teaching/Training, E-commerce.

### Machine Learning Internship Types and Stipend Insights

Internshala offers a variety of Machine Learning internship opportunities to match different work preferences:

* 118 full-time Machine Learning internships
* 66 part-time Machine Learning internships
* 120 work-from-home Machine Learning internships

#### Stipend Insights for Machine Learning Internships

Stipends for Machine Learning internship roles vary based on experience, skills, and industry demand:

* For Machine Learning internships: Stipend typically ranges from ₹1,000 to ₹75,000 per month.

### Top Companies Hiring for Machine Learning internships

Some of the most active companies currently recruiting for Machine Learning internships include:

* GRADTWIN SERVICES (OPC) PRIVATE LIMITED
* Echotalk
* NDFM Business World Pvt. Ltd.
* She Can Foundation
* Basti Ki Pathshala Foundation

Explore company pages and apply to verified Machine Learning internship openings directly on Internshala.

### Stay Updated with Machine Learning Internship Alerts

Don't miss out on new Machine Learning internship vacancies. Sign up for free internship alerts to receive the latest Machine Learning openings that match your profile. Stay ahead while finding Machine Learning internships that fit your career goals.

Join the pool of 21Mn+ students and get started with your career

PLAY STORE RATINGS

4.4

(47K Reviews)

Get it on Google Play

Must-have app for students

I got my first internship from here. Internshala is must for career oriented students. This app has a lot of opportunities for every kind of students.

Yogesh Singh

I landed a job at Amazon

I applied to Amazon and got the job! It was my dream. I wanted to get in tech but I was from electrical background. My friend suggested Data Science Placement Guarantee Course. In the course, I learnt SQL, Python, Tableau & worked on a lot of projects which came in handy in my interviews. I was able to explain the concepts and applications well. The placement team helped me with everything.

Yaswanth Mandapati

Placement guarantee works

100% guarantee de rahe the, mujhe 100% doubt tha ki placement hogi bhi ya nahi. Truth is I got a placement. I didn't have any idea of how to enter corporate, what kind of

======================================================================
TITLE: ‏٥٦١‏ من وظائف ‏Artificial Intelligence Intern‏ في ‏الهند‏
URL: https://in.linkedin.com/jobs/artificial-intelligence-intern-jobs
----------------------------------------------------------------------
احصل على إشعارات عندما يتم نشر وظيفة جديدة.

تعيين تنبيه

# ٥٦١ Artificial Intelligence Intern وظائف في الهند

* AI Prompt Engineer Internship in Pune

  ### AI Prompt Engineer Internship in Pune

  ماهاراشترا مدينة بوني الهند


  قبل ٥ساعة
* Artificial Intelligence (AI) Internship in Mumbai

  ### Artificial Intelligence (AI) Internship in Mumbai

  #### TAXOSMART

  منطقة مومباي الحضرية


  قبل ٣ أسبوع
* Intern - AI/ML

  ### Intern - AI/ML

  #### Tower Research Capital

  هاريانا جورجاون الهند


  قبل ١ أسبوع
* Agentic AI Intern

  ### Agentic AI Intern

  #### Mico

  كارناتاكا بانغالور الهند


  قبل ٢١ساعة
* Machine Learning Internship

  ### Machine Learning Internship

  #### Sparks To Ideas

  جوجارات أمريلي الهند

  كن من أول المتقدمين

  قبل ١شهر
* AI Generalist Intern

  ### AI Generalist Intern

  #### 360 Ghar

  هاريانا غورو غرام الهند


  قبل ١ أسبوع
* Artificial Intelligence (AI) Internship in Bangalore

  ### Artificial Intelligence (AI) Internship in Bangalore

  #### Simple Energy

  كارناتاكا بانغالور الهند


  قبل ٣ أسبوع
* Machine Learning Internship

  ### Machine Learning Internship

  #### Sparks To Ideas

  جوجارات بورباندار الهند

  كن من أول المتقدمين

  قبل ١شهر
* AI Agent Engineer Intern

  ### AI Agent Engineer Intern

  #### Lexsi Labs

  منطقة مومباي الحضرية


  قبل ١ أسبوع
* AI Intern

  ### AI Intern

  #### Honasa Consumer Ltd.

  هاريانا جوروجرام الهند


  قبل ١ أسبوع
* Machine Learning Intern

  ### Machine Learning Intern

  #### ERIC Robotics

  ماهاراشترا مدينة بوني الهند


  قبل ٢شهر
* AI Internship

  ### AI Internship

  #### Delaplex

  ماهاراشترا ناجبور أوربان الهند


  قبل ٢شهر
* GenAI Intern

  ### GenAI Intern

  #### Training Basket

  أوتار براديش نويدا الهند


  قبل ١ أيام
* AI Engineer Intern

  ### AI Engineer Intern

  #### Thommidhi

  منطقة كولكاتا وضواحيها


  قبل ١ أسبوع
* AI Intern

  ### AI Intern

  #### Faclon Labs

  منطقة مومباي الحضرية


  قبل ٣شهر
* ML Intern

  ### ML Intern

  #### Training Basket

  أوتار براديش نويدا الهند


  قبل ٦ أيام
* AI Engineer Intern

  ### AI Engineer Intern

  #### Discover Dollar Inc

  كارناتاكا شرق بنغالورو الهند


  قبل ٦ أيام
* AI Engineer/Applied AI Internship

  ### AI Engineer/Applied AI Internship

  #### InterviewGod

  الهند


  قبل ٤ أيام
* Artificial Intelligence Intern

  ### Artificial Intelligence Intern

  #### eTeam

  أوتار براديش نويدا الهند


  قبل ٢ أسبوع
* Full Stack AI Engineer — AI Agents Internship in Kompally, Hyderabad

  ### Full

======================================================================
TITLE: Internships in India for DA/DS/ML/AI Roles | Kaggle
URL: https://www.kaggle.com/getting-started/187186
----------------------------------------------------------------------
Kaggle uses cookies from Google to deliver and enhance the quality of its services and to analyze traffic.

Learn more

OK, Got it.

###### Something went wrong and this page crashed!

If the issue persists, it's likely a problem on our side.

```
Loading CSS chunk 7815 failed.\n(https://www.kaggle.com/static/assets/7815.e94de944d22d175f.css)

Error: Loading CSS chunk 7815 failed.\n(https://www.kaggle.com/static/assets/7815.e94de944d22d175f.css)
    at n.onerror.n.onload (https://www.kaggle.com/static/assets/runtime.js?v=79229d1b839f992f:1:13485)
```

======================================================================
TITLE: 145 machine learning intern jobs in India, October 2026 | Glassdoor
URL: https://www.glassdoor.co.in/Job/india-machine-learning-intern-jobs-SRCH_IL.0,5_IN115_KO6,29.htm
----------------------------------------------------------------------
Machine Learning Intern
Company: Optimspace.in
Location: Remote
Duration: 3 months
Opportunity: Full-time based on performance, with Certificate of Internship

About Optimspace.in

Optimspace.in provides students and graduates with hands-on learning opportunities and career growth in Machine Learning and Data Science.

Role Overview
As a Machine Learning Intern, you will work on real-world projects, enhancing your practical skills in data analysis and model development.
Responsibilities
✅ Design, test, and optimize machine learning models
✅ Analyze and preprocess datasets
✅ Develop algorithms and predictive models
✅ Use tools like TensorFlow, PyTorch, and Scikit-learn
✅ Document findings and create reports
Requirements
Enrolled in or a graduate of a relevant program (Computer Science, AI, Data Science, or related field)
Knowledge of machine learning concepts and algorithms
Proficiency in Python or R (preferred)
Strong analytical and teamwork skills
Benefits
Stipend: ₹7,500 - ₹15,000 (Performance-Based) (Paid)
✔ Hands-on machine learning experience
✔ Internship Certificate & Letter of Recommendation
✔ Real-world project contributions for your portfolio
How to Apply
Submit your application with "Data Analyst Intern Application" as the subject.
Note: Optimspace.in is an equal opportunity employer, welcoming diverse applicants.

Read authentic reviews with a Glassdoor account. Only apply to jobs you love.

In [9]:
import re

keywords = [
    "internship", "intern", "machine learning",
    "artificial intelligence", "apply", "location",
    "eligibility", "deadline", "requirements"
]

for page in result.results:
    text = page.text or ""

    lines = [
        re.sub(r"\s+", " ", line).strip()
        for line in text.splitlines()
        if line.strip()
    ]

    relevant = [
        line for line in lines
        if any(word in line.lower() for word in keywords)
    ]

    print("\n" + "=" * 55)
    print("COMPANY PAGE:", page.title)
    print("URL:", page.url)
    print("=" * 55)

    for line in relevant[:12]:
        print("•", line[:250])

=======================================================
COMPANY PAGE: Work with us
URL: https://machinelearning.apple.com/work-with-us
=======================================================
• Build amazing machine learning experiences with Apple. Discover opportunities for developers and researchers at Apple.
• ## Jobs in Machine Learning and AI
• Our machine learning research teams collaborate to deliver amazing experiences that improve the lives of millions of people every day.
• ## Internships in Machine Learning and AI
• Get hands-on machine learning experience with our researchers. Come to Apple as a student, and your team will welcome you as a full contributor.
• Explore internship opportunities
• The PhD fellowships in Machine Learning and AI were created to celebrate the contributions of students pursuing cutting-edge fundamental and applied machine learning research worldwide.
• Privacy Preserving Machine Learning
• Privacy Preserving Machine Learning
• The AIML Residency Program invites experts in various fields to apply their own domain expertise to innovate and build revolutionary machine learning and AI-powered products and experiences. As AI-based solutions spread across disciplines, the need f

=======================================================
COMPANY PAGE: Machine Learning Internships - 144 Intern Jobs in Oct 2026
URL: https://internshala.com/internships/machine-learning-internship/
=======================================================
• ## Machine Learning Internship Snapshot
• Looking for Machine Learning internships? Currently, there are 144 active Machine Learning internship vacancies from 130 companies across key sector(s) such as IT/Technology, Education/Teaching/Training, E-commerce.
• ### Machine Learning Internship Types and Stipend Insights
• Internshala offers a variety of Machine Learning internship opportunities to match different work preferences:
• * 118 full-time Machine Learning internships
• * 66 part-time Machine Learning internships
• * 120 work-from-home Machine Learning internships
• #### Stipend Insights for Machine Learning Internships
• Stipends for Machine Learning internship roles vary based on experience, skills, and industry demand:
• * For Machine Learning internships: Stipend typically ranges from ₹1,000 to ₹75,000 per month.
• ### Top Companies Hiring for Machine Learning internships
• Some of the most active companies currently recruiting for Machine Learning internships include:

=======================================================
COMPANY PAGE: ‏٥٦١‏ من وظائف ‏Artificial Intelligence Intern‏ في ‏الهند‏
URL: https://in.linkedin.com/jobs/artificial-intelligence-intern-jobs
=======================================================
• # ٥٦١ Artificial Intelligence Intern وظائف في الهند
• * AI Prompt Engineer Internship in Pune
• ### AI Prompt Engineer Internship in Pune
• * Artificial Intelligence (AI) Internship in Mumbai
• ### Artificial Intelligence (AI) Internship in Mumbai
• * Intern - AI/ML
• ### Intern - AI/ML
• * Agentic AI Intern
• ### Agentic AI Intern
• * Machine Learning Internship
• ### Machine Learning Internship
• * AI Generalist Intern

=======================================================
COMPANY PAGE: Internships in India for DA/DS/ML/AI Roles | Kaggle
URL: https://www.kaggle.com/getting-started/187186
=======================================================

=======================================================
COMPANY PAGE: 145 machine learning intern jobs in India, October 2026 | Glassdoor
URL: https://www.glassdoor.co.in/Job/india-machine-learning-intern-jobs-SRCH_IL.0,5_IN115_KO6,29.htm
=======================================================
• Machine Learning Intern
• Location: Remote
• Opportunity: Full-time based on performance, with Certificate of Internship
• Optimspace.in provides students and graduates with hands-on learning opportunities and career growth in Machine Learning and Data Science.
• As a Machine Learning Intern, you will work on real-world projects, enhancing your practical skills in data analysis and model development.
• ✅ Design, test, and optimize machine learning models
• Requirements
• Knowledge of machine learning concepts and algorithms
• ✔ Hands-on machine learning experience
• ✔ Internship Certificate & Letter of Recommendation
• How to Apply
• Submit your application with "Data Analyst Intern Application" as the subject.

In [10]:
# Search for individual AI/ML internship openings
search_queries = [
    "AI machine learning intern India apply job opening",
    "site:jobs.lever.co machine learning intern",
    "site:boards.greenhouse.io AI intern"
]

targeted_results = []

for query in search_queries:
    response = requests.get(
        "https://api.search.tinyfish.ai",
        headers={"X-API-Key": API_KEY},
        params={
            "query": query,
            "location": "IN",
            "language": "en"
        },
        timeout=60
    )

    print(f"\nQuery: {query} | Status: {response.status_code}")

    if response.ok:
        data = response.json()
        targeted_results.extend(data.get("results", []))
    else:
        print(response.text[:300])

# Remove duplicate URLs
seen = set()
individual_jobs = []

for item in targeted_results:
    url = item.get("url", "").strip()
    title = item.get("title", "").strip()

    if url and title and url not in seen:
        seen.add(url)
        individual_jobs.append({
            "Title": title,
            "Website": item.get("site_name", ""),
            "URL": url,
            "Description": item.get("snippet", "")
        })

jobs_df = pd.DataFrame(individual_jobs)

print("\nUnique search results:", len(jobs_df))
display(jobs_df)

Query: AI machine learning intern India apply job opening | Status: 200

Query: site:jobs.lever.co machine learning intern | Status: 200

Query: site:boards.greenhouse.io AI intern | Status: 200

Unique search results: 30

,Title,Website,URL,Description
0,293 Machine Learning Ai Internship In Mumbai J...,in.linkedin.com,https://in.linkedin.com/jobs/machine-learning-...,Today's top 293 Machine Learning Ai Internship...
1,Machine Learning Internships - 151 Intern Jobs...,internshala.com,https://internshala.com/internships/machine-le...,Apply for 151 verified machine learning intern...
2,"100 Ml Intern Job Vacancies in Mumbai, Maharas...",in.indeed.com,"https://in.indeed.com/q-ml-intern-l-mumbai,-ma...","153 Ml Intern jobs available in Mumbai, Mahara..."
3,221 Ai ml intern jobs in India - Glassdoor,www.glassdoor.co.in,https://www.glassdoor.co.in/Job/ai-ml-intern-j...,221 open jobs for Ai ml intern. AI/ML Intern (...
4,154 Machine Learning Intern Job Vacancies In M...,www.naukri.com,https://www.naukri.com/machine-learning-intern...,Apply To Machine Learning Intern Jobs In Mumba...
5,Machine Learning Internships in India (297 ope...,in.prosple.com,https://in.prosple.com/machine-learning-intern...,Find open Machine Learning Internships in Indi...
6,507 Artificial Intelligence Intern jobs in India,in.linkedin.com,https://in.linkedin.com/jobs/artificial-intell...,507 Artificial Intelligence Intern Jobs in Ind...
7,Machine Learning and Artificial Intelligence I...,www.instahyre.com,https://www.instahyre.com/machine-learning-and...,Apply to 1089 Machine Learning and Artificial ...
8,AI and machine learning jobs in India (127 ope...,www.insiderone.in,https://www.insiderone.in/jobs/for/ai-ml/in/india,AI and machine learning jobs in India ; Intern...
9,Artificial Intelligence (AI) Internships - 215...,internshala.com,https://internshala.com/internships/artificial...,Find Artificial Intelligence (AI) internships ...
10,Shield AI - Summer 2027 - Software Engineer In...,jobs.lever.co,https://jobs.lever.co/shieldai/8c850c75-081d-4...,"Machine Learning: Train, evaluate, and integra..."
11,Data Scientist Intern - GoTo Group,jobs.lever.co,https://jobs.lever.co/GoToGroup/dff2a165-d111-...,"Over the first six months, you'll gain hands-o..."
12,Robotics Research Intern - Post-Training,jobs.lever.co,https://jobs.lever.co/tri/186808f9-464c-4f22-9...,This is a paid 12-week internship opportunity ...
13,Sprinto - AI Implementation Intern,jobs.lever.co,https://jobs.lever.co/Sprinto/6dfd5f41-57b6-40...,"In this internship, you'll have the opportunit..."
14,Human Interactive Driving Intern – World Models,jobs.lever.co,https://jobs.lever.co/tri/63d61db3-ac43-4c0d-8...,This is a paid 12-week internship opportunity ...
15,Whiterabbit.ai - Research Scientist Intern (2026),jobs.lever.co,https://jobs.lever.co/whiterabbit/c4333d64-7fc...,Must Have Experience · Experience with deep le...
16,Immuta - Product Research Internship - Summer ...,jobs.lever.co,https://jobs.lever.co/immuta/18aabf0a-8b27-4b7...,Apply research methods to practical problems i...
17,Machine Learning Engineer - Data Mining & VLM ...,jobs.lever.co,https://jobs.lever.co/zoox/7206fd97-14e4-43a0-...,"Coursework in machine learning, computer visio..."
18,Data Science Intern - QuantCo,jobs.lever.co,https://jobs.lever.co/quantco-/a9862eb3-bbfa-4...,In-depth understanding of mathematical and sta...
19,"Research Scientist Intern, Robot Learning & Ma...",jobs.lever.co,https://jobs.lever.co/field-ai/b37569c3-d07f-4...,"We are offering spring, summer, and fall 2027 ..."
20,Delight Careers: Join the AI-Native Team Build...,boards.greenhouse.io,https://boards.greenhouse.io/sendbird,Explore delight careers and join a global team...
21,Careers at Klaviyo,boards.greenhouse.io,https://boards.greenhouse.io/klaviyo/jobs/7855...,"Here at Klaviyo, we're looking for ambitious, ..."
22,Job Title Not Provided | Careers at Jump Trading,boards.greenhouse.io,https://boards.greenhouse.io/jumptrading/jobs/...,"We empower exceptional talents in Mathematics,..."
23,Job Application for Marketing Intern at Liberate,boards.greenhouse.io,https://boards.greenhouse.io/liberate/jobs/545...,Liberate's AI Marketing Internship is a rare c...
24,Product Design Intern (2027 Start) - Databricks,boards.greenhouse.io,https://boards.greenhouse.io/databricks/jobs/8...,You have a proven ability to efficiently build...
25,Careers,boards.greenhouse.io,https://boards.greenhouse.io/relativity/jobs/6...,Relativity is a place for builders with big id...
26,Research Engineer Intern (Fall 2026),boards.greenhouse.io,https://boards.greenhouse.io/cloudflare/jobs/8...,We value candidates who have the instinct to s...
27,Graph database jobs | Career opportunities at ...,boards.greenhouse.io,https://boards.greenhouse.io/neo4j/jobs/470521...,Help the world make sense of data at Neo4j. Ex...
28,Job Application for Strategic Project Intern a...,boards.greenhouse.io,https://boards.greenhouse.io/wonderstudios/job...,Strategic Project Intern. Start Date: January ...
29,Careers | About Udemy,boards.greenhouse.io,https://boards.greenhouse.io/udemy/jobs/640973,"Together, we're shaping how the world discover..."

In [11]:
from urllib.parse import urlparse

def looks_like_job_page(row):
    url = row["URL"].lower()
    title = row["Title"].lower()
    domain = urlparse(url).netloc

    # Exclude broad job-search and category pages
    broad_page_terms = [
        "/jobs/", "/internships/", "/job-search",
        "/q-", "/job/india-", "/search?"
    ]

    if any(term in url for term in broad_page_terms):
        return False

    # Prioritize common individual-job URL patterns
    individual_patterns = [
        "jobs.lever.co/",
        "boards.greenhouse.io/",
        "job-boards.greenhouse.io/",
        "jobs.ashbyhq.com/"
    ]

    if any(pattern in url for pattern in individual_patterns):
        return True

    # Keep other URLs for inspection if their titles
    # look like specific roles rather than collections.
    collection_terms = [
        "jobs in india", "internships in india",
        "job vacancies", "open jobs", "intern jobs"
    ]

    return not any(term in title for term in collection_terms)

jobs_df["Likely individual opening"] = jobs_df.apply(
    looks_like_job_page, axis=1
)

candidates_df = jobs_df[
    jobs_df["Likely individual opening"]
].copy()

print("Candidate URLs:", len(candidates_df))
display(candidates_df[["Title", "Website", "URL"]])

Candidate URLs: 11

,Title,Website,URL
10,Shield AI - Summer 2027 - Software Engineer In...,jobs.lever.co,https://jobs.lever.co/shieldai/8c850c75-081d-4...
11,Data Scientist Intern - GoTo Group,jobs.lever.co,https://jobs.lever.co/GoToGroup/dff2a165-d111-...
12,Robotics Research Intern - Post-Training,jobs.lever.co,https://jobs.lever.co/tri/186808f9-464c-4f22-9...
13,Sprinto - AI Implementation Intern,jobs.lever.co,https://jobs.lever.co/Sprinto/6dfd5f41-57b6-40...
14,Human Interactive Driving Intern – World Models,jobs.lever.co,https://jobs.lever.co/tri/63d61db3-ac43-4c0d-8...
15,Whiterabbit.ai - Research Scientist Intern (2026),jobs.lever.co,https://jobs.lever.co/whiterabbit/c4333d64-7fc...
16,Immuta - Product Research Internship - Summer ...,jobs.lever.co,https://jobs.lever.co/immuta/18aabf0a-8b27-4b7...
17,Machine Learning Engineer - Data Mining & VLM ...,jobs.lever.co,https://jobs.lever.co/zoox/7206fd97-14e4-43a0-...
18,Data Science Intern - QuantCo,jobs.lever.co,https://jobs.lever.co/quantco-/a9862eb3-bbfa-4...
19,"Research Scientist Intern, Robot Learning & Ma...",jobs.lever.co,https://jobs.lever.co/field-ai/b37569c3-d07f-4...
20,Delight Careers: Join the AI-Native Team Build...,boards.greenhouse.io,https://boards.greenhouse.io/sendbird

In [12]:
# Fetch up to 10 candidate job pages
from tinyfish import TinyFish
import os

os.environ["TINYFISH_API_KEY"] = API_KEY
client = TinyFish()

urls_to_fetch = (
    candidates_df["URL"]
    .dropna()
    .drop_duplicates()
    .head(10)
    .tolist()
)

fetch_result = client.fetch.get_contents(
    urls=urls_to_fetch,
    format="markdown",
    ttl=0,
    purpose=(
        "Extract the individual job title, hiring company, "
        "location, internship or employment type, requirements, "
        "application URL, and closing date if available. "
        "Determine whether the page describes a specific vacancy."
    )
)

print("Pages successfully fetched:", len(fetch_result.results))
print("Fetch errors:", len(fetch_result.errors))

for page in fetch_result.results:
    print("\n" + "=" * 55)
    print("TITLE:", page.title)
    print("URL:", page.url)
    print((page.text or "")[:1200])

for error in fetch_result.errors:
    print("\nFailed:", error.url, "|", error.error)

Pages successfully fetched: 10
Fetch errors: 0

=======================================================
TITLE: Shield AI - Summer 2027 - Software Engineer Intern
URL: https://jobs.lever.co/shieldai/8c850c75-081d-4d09-bebf-096379a93010
## Summer 2027 - Software Engineer Intern

San Diego, California / Washington, D.C. / Dallas, Texas / Seattle, Washington

Campus Recruiting – Software /

Intern /

On-site

apply for this job

Shield AI is a venture-backed defense-tech company with the mission of protecting service members and civilians with intelligent systems. Its products include Hivemind autonomy software, V-BAT and X-BAT aircraft, and Aechelon simulation and synthetic reality technologies. With offices and facilities across the U.S., Europe, the Middle East, and Asia-Pacific, Shield AI’s technology actively supports operations worldwide. For more information, visit www.shield.ai. Follow Shield AI on LinkedIn, X, Instagram, and YouTube.

Our Summer Internship program is a wonderful opportunity for Fall and Spring graduates to immerse themselves in an innovative and mission driven culture. Our paid internship program will provide you with hands on mentorship, an opportunity to add real contribution to our company via your internship project, and a possible job offer at the end. You will have the chance to make lifelong friendships, expand your network, and learn all about what it's like to work in a high-growth

=======================================================
TITLE: GoTo Group - Data Scientist Intern
URL: https://jobs.lever.co/GoToGroup/dff2a165-d111-4542-bfec-ec3856892275
## Data Scientist Intern

Jakarta

FinTech - Data – - /

Internship /

Remote

apply for this job

**About the Role**

We are looking for a dynamic, energetic intern to join our team and contribute to the development of our in-house Large Language Model (LLM). In this role, you'll tackle the challenges of data collection, validation, and labeling, directly impacting the quality and effectiveness of our LLM. You'll work closely with our data science and engineering teams, participating in daily standups, and collaborating on live production projects. Over the first six months, you’ll gain hands-on experience in managing and preparing large datasets, ensuring the quality of our AI models, and contributing to cutting-edge AI projects that drive real business value.

### What You Will Do

* Collect and validate data from various sources to train our LLM.
* Analyze, review, and accurately label text data based on predefined guidelines.
* Ensure the consistency and quality of labeled data by following established protocols.
* Provide feedback on labeling guidelines and suggest improvements.
* Work closely with data science and engineering teams to meet project goals.
* Participate in dai

=======================================================
TITLE: Toyota Research Institute - Robotics Research Intern - Post-Training
URL: https://jobs.lever.co/tri/186808f9-464c-4f22-9d7d-4372ef272ff0
## Robotics Research Intern - Post-Training

Los Altos, CA

HQ Robotics – Internships - Spring 2027 /

Intern /

Hybrid

apply for this job

At Toyota Research Institute (TRI), we’re on a mission to improve the quality of human life. We’re developing new tools and capabilities to amplify the human experience. To lead this transformative shift in mobility, we’ve built a world-class team advancing the state of the art in AI, robotics, driving, and material sciences.

This is a paid 12-week internship opportunity and is a hybrid, in-office role.

### Qualifications

* Currently pursuing a Ph.D. in Computer Science, Machine Learning, Robotics, or a related field.
* Research experience in robot learning, reinforcement learning, imitation learning, generative modeling, world models, or a related area.
* Interest in open research problems involving large-scale machine learning grounded in physical systems.
* Proficiency in Python and a deep-learning framework such as PyTorch.
* Ability to collaborate effectively with researchers and engineers and communicate research findings clearly.

### Bonus Qualifications

* Experience with pretrained generalist policies, foundation models, or large-

=======================================================
TITLE: Sprinto - AI Implementation Intern
URL: https://jobs.lever.co/Sprinto/6dfd5f41-57b6-40e8-9eab-ba4083c1a7c4
## AI Implementation Intern

Bengaluru

AI Office /

Remote /

Remote

apply for this job

Sprinto is an **Autonomous Trust Platform** that centralizes trust requirements across **security frameworks, vendors, and customers.**

Sprinto autonomously executes tasks needed to maintain trust across compliance, audits, risk management, vendor risk, privacy, and AI governance, enabling organizations to maintain a strong, reliable trust posture without draining operational bandwidth and resources on repetitive tasks.

Backed by top-tier investors such as Accel, Elevation, and Blume Ventures, we’ve **raised** **$31.8M** in funding to fuel our mission. Trusted by over **4,000 organizations across 75 countries**, Sprinto helps organizations stay audit-ready, manage real-time risks, and scale fearlessly. With **300+ native integrations** and AI-driven automation, Sprinto supports **200+ global security standards natively**, including SOC 2, ISO 27001, GDPR, HIPAA, PCI-DSS, and more. Sprinto's extensible architecture enables organizations to build and support an infinite number of custom integrations and frameworks.

**Founded in 2020** by second-time founders Girish Redekar and Raghuveer Kanc

=======================================================
TITLE: Toyota Research Institute - Human Interactive Driving Intern – World Models
URL: https://jobs.lever.co/tri/63d61db3-ac43-4c0d-8b9b-5006e3b92149
## Human Interactive Driving Intern – World Models

Los Altos, CA

Human Interactive Driving – Internships - Fall 2026 /

Intern /

Hybrid

apply for this job

At Toyota Research Institute (TRI), we’re on a mission to improve the quality of human life. We’re developing new tools and capabilities to amplify the human experience. To lead this transformative shift in mobility, we’ve built a world-class team advancing the state of the art in AI, robotics, driving, and material sciences.

This is a paid 12-week internship opportunity and is a hybrid, in-office role.

**The Team**

You’ll be joining a multidisciplinary research team focused on developing a world foundation model for driving—a unified, transferable representation of driving knowledge built from large-scale real-world and simulated data.  Together, we are tackling the complex challenges of multi-agent interaction, causal reasoning, and embodied intelligence in highly dynamic, real-world driving environments. Our approach is inspired by cutting-edge generative modeling techniques and powered by scalable infrastructure and open-source data, and we work closely with engineers to deploy our models in simulation and on hardware

=======================================================
TITLE: Whiterabbit.ai - Research Scientist Intern (2026)
URL: https://jobs.lever.co/whiterabbit/c4333d64-7fcf-4862-9cf0-c6b090ca8ca1
## Research Scientist Intern (2026)

Remote

Research /

Intern /

Remote

apply for this job

We are looking for a Research Scientist Intern to push the state of the art of our AI models. As a Research Scientist Intern at Whiterabbit.ai, you will:

- Play a key role in architecting the algorithms and models that will power our products

- Train on a dedicated high-performance compute cluster specialized for deep learning research

- Work with doctors and healthcare professionals to identify serious problems and leverage their domain expertise to build robust solutions

- Remain an active contributor to the research community by partnering with universities and  publishing high impact papers

**Who we are:**

Our mission at Whiterabbit.ai is to save lives and eliminate suffering through the early detection of  cancer with artificial intelligence. We collaborate closely with one of the top medical schools in the  country and have exclusive access to one of the world’s largest cancer datasets with millions of images.  We invent algorithms that make doctors more productive, more accurate, and more capable. We build products and services with a relentless focus on transforming the pati

=======================================================
TITLE: Immuta - Product Research Internship - Summer 2027
URL: https://jobs.lever.co/immuta/18aabf0a-8b27-4b7d-8a96-6995a7f8847b
## Product Research Internship - Summer 2027

Columbus, OH

Internships – Internships /

Intern /

Hybrid

apply for this job

Immuta is the Data Authorization Company, helping the world’s largest organizations control who, and what, can access their data.

The way enterprises access data is fundamentally changing. Organizations are racing to put data to work across analytics and AI, while AI copilots and agents are emerging as an entirely new class of data consumer. Traditional approaches built around tickets, static permissions, and manual approvals were not designed for this speed, scale, or complexity.

Immuta provides the authorization layer for modern data and AI. Our platform enables organizations to provision governed access to data by policy, by request, and dynamically for AI agents, so people and AI can access the data they need while enterprises maintain security, compliance, and control.

For Chief Data Officers, that means making enterprise data dramatically easier to access and use without giving up governance. For AI leaders, it means giving AI agents secure, governed access to enterprise data so they can move from experimentation into production.

Founded in 2015,

=======================================================
TITLE: Zoox - Contract Student Worker - Machine Learning Engineer - Data Mining & VLM (Full-time)
URL: https://jobs.lever.co/zoox/7206fd97-14e4-43a0-b903-ba65dfeee53e
## Contract Student Worker - Machine Learning Engineer - Data Mining & VLM (Full-time)

Foster City, CA

Zoox Internships – Data Science /

Contract /

Hybrid

apply for this job

**About Zoox**

Zoox is an autonomous ridehailing company building the world's first purpose-built robotaxi — fully electric, bidirectional, with no steering wheel or driver's seat. Backed by Amazon and founded to make transportation safer, cleaner, and more accessible, Zoox designs its vehicles entirely around the rider. We're currently operating in Las Vegas and San Francisco, with Austin and Miami on the horizon, and testing underway across seven U.S. markets.

**About Our Part-Time Student Worker Program**

Zoox's part-time student worker program puts you at the center of one of the most ambitious challenges in transportation. You'll contribute to real projects, work alongside engineers and researchers pushing the boundaries of autonomous technology, and gain experience that goes well beyond the classroom. We're looking for students who bring strong academic foundations, curiosity that doesn't stop at coursework, and a drive to be part of something that matters.

**Role Overview**

Support Zoox's Rule

=======================================================
TITLE: QuantCo - Data Science Intern
URL: https://jobs.lever.co/quantco-/a9862eb3-bbfa-4cdc-862d-ad614f20b1e4
## Data Science Intern

Europe

Data Science /

Full-Time /

On-site

apply for this job

Data Science Interns at QuantCo will learn what it takes to create impact from data: identifying the right framework and questions to translate a business challenge into a statistical problem; locating and combining data sources as well as transforming large datasets; running in-depth analyses; building machine learning models that automate large-scale decisions and integrating them into live business processes; and interpreting, visualizing, and communicating results to internal and external stakeholders.

### We are looking for team players who have excellent quantitative abilities and:

* A degree in economics, statistics, mathematics, computer science, engineering, physics, or similar fields at a leading university
* In-depth understanding of mathematical and statistical concepts behind most common machine learning techniques and an interest in causal inference questions
* Experience in coding and working with data (from a previous research or industry internship or extensive course projects)
* Ability to see solutions and opportunities that others do not see
* High level of commitment and

=======================================================
TITLE: FieldAI - Robotics Research Intern, Robot Learning & Manipulation (Spring, Summer & Fall 2027)
URL: https://jobs.lever.co/field-ai/b37569c3-d07f-4968-82dc-44020f34e54e
## Robotics Research Intern, Robot Learning & Manipulation (Spring, Summer & Fall 2027)

Irvine, CA

Engineering – Mission, Interaction & Insights /

Internship /

On-site

apply for this job

FieldAI’s Irvine team is where embodied AI meets real robots, real sensors, and real field deployments. Based in the heart of Southern California’s robotics ecosystem, we build risk-aware, reliable, field-ready AI systems that solve the hardest problems in robotics and unlock the full potential of embodied intelligence. If you want your work to ship, get tested on hardware, and improve through real deployments, Irvine is the place. We go beyond typical data-driven approaches or pure transformer-only architectures, combining rigorous engineering with learning systems proven in globally deployed solutions that deliver results today and get better every time our robots run in the field.

### About the Internship

We are offering Spring, Summer, and Fall 2027 research internships in the Irvine office for Master’s and PhD students advancing robotic manipulation.

You will investigate how robots can perform useful physical tasks reliably across diverse objects, environments, and robot platforms. Wo

In [13]:
import re
import pandas as pd

def extract_field(text, patterns):
    for pattern in patterns:
        match = re.search(pattern, text, re.I | re.M)
        if match:
            return match.group(1).strip()
    return "Not specified"

structured_jobs = []

for page in fetch_result.results:
    text = page.text or ""

    title = (
        re.search(r"^#\s+(.+)", text, re.M)
        or re.search(r"^TITLE:\s*(.+)", text, re.M)
    )

    title = title.group(1).strip() if title else page.title

    company = extract_field(text, [
        r"Company:\s*(.+)",
        r"About\s+([A-Z][A-Za-z0-9& .-]+)"
    ])

    location = extract_field(text, [
        r"Location:\s*(.+)",
        r"Locations?:\s*(.+)"
    ])

    structured_jobs.append({
        "Job Title": title,
        "Company": company,
        "Location": location,
        "Job URL": page.url,
        "Page Text Preview": re.sub(r"\s+", " ", text)[:350]
    })

structured_df = pd.DataFrame(structured_jobs)

print("Pages processed:", len(structured_df))
display(structured_df)

Pages processed: 10

,Job Title,Company,Location,Job URL,Page Text Preview
0,Shield AI - Summer 2027 - Software Engineer In...,what it,Not specified,https://jobs.lever.co/shieldai/8c850c75-081d-4...,## Summer 2027 - Software Engineer Intern San ...
1,GoTo Group - Data Scientist Intern,the Role,Not specified,https://jobs.lever.co/GoToGroup/dff2a165-d111-...,## Data Scientist Intern Jakarta FinTech - Dat...
2,Toyota Research Institute - Robotics Research ...,and,Not specified,https://jobs.lever.co/tri/186808f9-464c-4f22-9...,## Robotics Research Intern - Post-Training Lo...
3,Sprinto - AI Implementation Intern,the impact they create. If something can be im...,Not specified,https://jobs.lever.co/Sprinto/6dfd5f41-57b6-40...,## AI Implementation Intern Bengaluru AI Offic...
4,Toyota Research Institute - Human Interactive ...,and,Not specified,https://jobs.lever.co/tri/63d61db3-ac43-4c0d-8...,## Human Interactive Driving Intern – World Mo...
5,Whiterabbit.ai - Research Scientist Intern (2026),how your data is processed,Not specified,https://jobs.lever.co/whiterabbit/c4333d64-7fc...,## Research Scientist Intern (2026) Remote Res...
6,Immuta - Product Research Internship - Summer ...,THE TEAM,Not specified,https://jobs.lever.co/immuta/18aabf0a-8b27-4b7...,## Product Research Internship - Summer 2027 C...
7,Zoox - Contract Student Worker - Machine Learn...,Zoox,Not specified,https://jobs.lever.co/zoox/7206fd97-14e4-43a0-...,## Contract Student Worker - Machine Learning ...
8,QuantCo - Data Science Intern,QuantCo,Not specified,https://jobs.lever.co/quantco-/a9862eb3-bbfa-4...,## Data Science Intern Europe Data Science / F...
9,"FieldAI - Robotics Research Intern, Robot Lear...",the Internship,Not specified,https://jobs.lever.co/field-ai/b37569c3-d07f-4...,"## Robotics Research Intern, Robot Learning & ..."

In [14]:
import pandas as pd
import re
from urllib.parse import urlparse

def get_company_from_url(url):
    host = urlparse(url).netloc.lower()

    if host == "jobs.lever.co":
        parts = urlparse(url).path.strip("/").split("/")
        if parts:
            return parts[0].replace("-", " ").title()

    if host in ["boards.greenhouse.io", "job-boards.greenhouse.io"]:
        parts = urlparse(url).path.strip("/").split("/")
        if parts:
            return parts[0].replace("-", " ").title()

    return host.removeprefix("www.")

clean_jobs = []

for page in fetch_result.results:
    text = page.text or ""

    # Use the first Markdown heading as the job title
    match = re.search(r"^#\s+(.+)", text, re.MULTILINE)
    title = match.group(1).strip() if match else page.title

    clean_jobs.append({
        "Job Title": title,
        "Company": get_company_from_url(page.url),
        "Location": "Needs verification",
        "Job URL": page.url,
        "Description": re.sub(r"\s+", " ", text)[:500]
    })

clean_jobs_df = pd.DataFrame(clean_jobs)

display(clean_jobs_df)

,Job Title,Company,Location,Job URL,Description
0,Shield AI - Summer 2027 - Software Engineer In...,Shieldai,Needs verification,https://jobs.lever.co/shieldai/8c850c75-081d-4...,## Summer 2027 - Software Engineer Intern San ...
1,GoTo Group - Data Scientist Intern,Gotogroup,Needs verification,https://jobs.lever.co/GoToGroup/dff2a165-d111-...,## Data Scientist Intern Jakarta FinTech - Dat...
2,Toyota Research Institute - Robotics Research ...,Tri,Needs verification,https://jobs.lever.co/tri/186808f9-464c-4f22-9...,## Robotics Research Intern - Post-Training Lo...
3,Sprinto - AI Implementation Intern,Sprinto,Needs verification,https://jobs.lever.co/Sprinto/6dfd5f41-57b6-40...,## AI Implementation Intern Bengaluru AI Offic...
4,Toyota Research Institute - Human Interactive ...,Tri,Needs verification,https://jobs.lever.co/tri/63d61db3-ac43-4c0d-8...,## Human Interactive Driving Intern – World Mo...
5,Whiterabbit.ai - Research Scientist Intern (2026),Whiterabbit,Needs verification,https://jobs.lever.co/whiterabbit/c4333d64-7fc...,## Research Scientist Intern (2026) Remote Res...
6,Immuta - Product Research Internship - Summer ...,Immuta,Needs verification,https://jobs.lever.co/immuta/18aabf0a-8b27-4b7...,## Product Research Internship - Summer 2027 C...
7,Zoox - Contract Student Worker - Machine Learn...,Zoox,Needs verification,https://jobs.lever.co/zoox/7206fd97-14e4-43a0-...,## Contract Student Worker - Machine Learning ...
8,QuantCo - Data Science Intern,Quantco,Needs verification,https://jobs.lever.co/quantco-/a9862eb3-bbfa-4...,## Data Science Intern Europe Data Science / F...
9,"FieldAI - Robotics Research Intern, Robot Lear...",Field Ai,Needs verification,https://jobs.lever.co/field-ai/b37569c3-d07f-4...,"## Robotics Research Intern, Robot Learning & ..."

In [15]:
import re
import pandas as pd

def extract_location(text):
    patterns = [
        r"(?im)^Location\s*:\s*(.+)$",
        r"(?im)^Locations?\s*:\s*(.+)$",
        r"(?im)^Location\s*\n+\s*(.+)$",
        r"(?im)^Office location\s*:\s*(.+)$"
    ]

    for pattern in patterns:
        match = re.search(pattern, text)
        if match:
            value = match.group(1).strip()
            if len(value) < 100:
                return value

    return "Not found on page"

def extract_job_type(text):
    if re.search(r"\bintern(ship)?\b", text, re.I):
        return "Internship"
    if re.search(r"\bfull[- ]time\b", text, re.I):
        return "Full-time"
    if re.search(r"\bpart[- ]time\b", text, re.I):
        return "Part-time"
    return "Not specified"

improved_jobs = []

for page in fetch_result.results:
    text = page.text or ""
    row = clean_jobs_df.loc[
        clean_jobs_df["Job URL"] == page.url
    ]

    if row.empty:
        continue

    item = row.iloc[0].to_dict()
    item["Location"] = extract_location(text)
    item["Job Type"] = extract_job_type(text)
    item["Page Title"] = page.title
    improved_jobs.append(item)

improved_jobs_df = pd.DataFrame(improved_jobs)

display(improved_jobs_df[
    ["Job Title", "Company", "Location",
     "Job Type", "Job URL"]
])

,Job Title,Company,Location,Job Type,Job URL
0,Shield AI - Summer 2027 - Software Engineer In...,Shieldai,Not found on page,Internship,https://jobs.lever.co/shieldai/8c850c75-081d-4...
1,GoTo Group - Data Scientist Intern,Gotogroup,Not found on page,Internship,https://jobs.lever.co/GoToGroup/dff2a165-d111-...
2,Toyota Research Institute - Robotics Research ...,Tri,Not found on page,Internship,https://jobs.lever.co/tri/186808f9-464c-4f22-9...
3,Sprinto - AI Implementation Intern,Sprinto,Not found on page,Internship,https://jobs.lever.co/Sprinto/6dfd5f41-57b6-40...
4,Toyota Research Institute - Human Interactive ...,Tri,Not found on page,Internship,https://jobs.lever.co/tri/63d61db3-ac43-4c0d-8...
5,Whiterabbit.ai - Research Scientist Intern (2026),Whiterabbit,Not found on page,Internship,https://jobs.lever.co/whiterabbit/c4333d64-7fc...
6,Immuta - Product Research Internship - Summer ...,Immuta,Not found on page,Internship,https://jobs.lever.co/immuta/18aabf0a-8b27-4b7...
7,Zoox - Contract Student Worker - Machine Learn...,Zoox,Not found on page,Internship,https://jobs.lever.co/zoox/7206fd97-14e4-43a0-...
8,QuantCo - Data Science Intern,Quantco,Not found on page,Internship,https://jobs.lever.co/quantco-/a9862eb3-bbfa-4...
9,"FieldAI - Robotics Research Intern, Robot Lear...",Field Ai,Not found on page,Internship,https://jobs.lever.co/field-ai/b37569c3-d07f-4...

In [16]:
import re
import pandas as pd

# User preferences
preferred_roles = ["AI", "Machine Learning", "Data Science"]
preferred_locations = ["India", "Remote"]
preferred_skills = ["Python", "SQL", "Machine Learning"]
preferred_level = "Internship"

def calculate_match(job):
    title = str(job["Job Title"]).lower()
    description = str(job.get("Description", "")).lower()
    text = title + " " + description

    score = 0
    reasons = []

    # Role match: 40 points
    matched_roles = [
        role for role in preferred_roles
        if role.lower() in text
    ]
    if matched_roles:
        score += min(40, 20 * len(matched_roles))
        reasons.append("Roles: " + ", ".join(matched_roles))

    # Skill match: 40 points
    matched_skills = [
        skill for skill in preferred_skills
        if skill.lower() in text
    ]
    if matched_skills:
        score += min(40, 40 * len(matched_skills) / len(preferred_skills))
        reasons.append("Skills: " + ", ".join(matched_skills))

    # Level match: 20 points
    if preferred_level.lower() in text:
        score += 20
        reasons.append("Internship-level wording found")

    return pd.Series({
        "Match Score": round(score),
        "Match Reasons": "; ".join(reasons) if reasons else "Weak keyword match"
    })

match_results = improved_jobs_df.apply(calculate_match, axis=1)
ranked_jobs_df = pd.concat(
    [improved_jobs_df, match_results], axis=1
).sort_values("Match Score", ascending=False)

display(ranked_jobs_df[
    ["Job Title", "Company", "Match Score",
     "Match Reasons", "Job URL"]
])

,Job Title,Company,Match Score,Match Reasons,Job URL
7,Zoox - Contract Student Worker - Machine Learn...,Zoox,73,"Roles: AI, Machine Learning, Data Science; Ski...",https://jobs.lever.co/zoox/7206fd97-14e4-43a0-...
1,GoTo Group - Data Scientist Intern,Gotogroup,60,"Roles: AI, Data Science; Internship-level word...",https://jobs.lever.co/GoToGroup/dff2a165-d111-...
8,QuantCo - Data Science Intern,Quantco,53,"Roles: Machine Learning, Data Science; Skills:...",https://jobs.lever.co/quantco-/a9862eb3-bbfa-4...
6,Immuta - Product Research Internship - Summer ...,Immuta,40,Roles: AI; Internship-level wording found,https://jobs.lever.co/immuta/18aabf0a-8b27-4b7...
2,Toyota Research Institute - Robotics Research ...,Tri,40,Roles: AI; Internship-level wording found,https://jobs.lever.co/tri/186808f9-464c-4f22-9...
4,Toyota Research Institute - Human Interactive ...,Tri,40,Roles: AI; Internship-level wording found,https://jobs.lever.co/tri/63d61db3-ac43-4c0d-8...
9,"FieldAI - Robotics Research Intern, Robot Lear...",Field Ai,40,Roles: AI; Internship-level wording found,https://jobs.lever.co/field-ai/b37569c3-d07f-4...
0,Shield AI - Summer 2027 - Software Engineer In...,Shieldai,20,Roles: AI,https://jobs.lever.co/shieldai/8c850c75-081d-4...
5,Whiterabbit.ai - Research Scientist Intern (2026),Whiterabbit,20,Roles: AI,https://jobs.lever.co/whiterabbit/c4333d64-7fc...
3,Sprinto - AI Implementation Intern,Sprinto,20,Roles: AI,https://jobs.lever.co/Sprinto/6dfd5f41-57b6-40...

In [17]:
import ipywidgets as widgets
from IPython.display import display, clear_output

role_input = widgets.Text(
    value="AI / Machine Learning Intern",
    description="Role:",
    placeholder="e.g. Data Scientist"
)

location_input = widgets.Text(
    value="India",
    description="Location:",
    placeholder="e.g. Remote, Bengaluru"
)

skills_input = widgets.Text(
    value="Python, SQL, Machine Learning",
    description="Skills:",
    placeholder="Enter comma-separated skills"
)

level_input = widgets.Dropdown(
    options=["Internship", "Entry-level", "Any"],
    value="Internship",
    description="Level:"
)

search_button = widgets.Button(
    description="Find Matching Jobs",
    button_style="success",
    icon="search"
)

output = widgets.Output()

def find_matching_jobs(button):
    with output:
        clear_output(wait=True)

        roles = [
            word.strip().lower()
            for word in role_input.value.split("/")
            if word.strip()
        ]

        locations = [
            word.strip().lower()
            for word in location_input.value.split(",")
            if word.strip()
        ]

        skills = [
            word.strip().lower()
            for word in skills_input.value.split(",")
            if word.strip()
        ]

        def score_job(job):
            title = str(job.get("Job Title", "")).lower()
            description = str(job.get("Description", "")).lower()
            location = str(job.get("Location", "")).lower()
            text = title + " " + description

            role_score = (
                sum(1 for role in roles if role in title)
                / max(len(roles), 1)
            )

            skill_score = (
                sum(1 for skill in skills if skill in text)
                / max(len(skills), 1)
            )

            location_score = (
                1.0 if any(loc in location for loc in locations) else 0.0
            )

            level_score = (
                1.0 if level_input.value == "Any"
                or level_input.value.lower() in text
                else 0.0
            )

            score = (
                0.40 * role_score
                + 0.35 * skill_score
                + 0.15 * location_score
                + 0.10 * level_score
            ) * 100

            return round(score)

        ranked = improved_jobs_df.copy()
        ranked["Match Score"] = ranked.apply(score_job, axis=1)
        ranked = ranked.sort_values("Match Score", ascending=False)

        display(ranked[
            ["Job Title", "Company", "Location",
             "Match Score", "Job URL"]
        ])

search_button.on_click(find_matching_jobs)

display(widgets.VBox([
    role_input,
    location_input,
    skills_input,
    level_input,
    search_button,
    output
]))

VBox(children=(Text(value='AI / Machine Learning Intern', description='Role:', placeholder='e.g. Data Scientis…

In [19]:
def search_live_jobs(role, location, skills, level):
    query = (
        f"{role} {level} jobs internships "
        f"{skills} in {location} apply"
    )

    response = requests.get(
        "https://api.search.tinyfish.ai",
        headers={"X-API-Key": API_KEY},
        params={
            "query": query,
            "location": "IN",
            "language": "en"
        },
        timeout=60
    )

    response.raise_for_status()
    data = response.json()

    return data.get("results", [])

In [20]:
live_results = search_live_jobs(
    role="AI / Machine Learning Intern",
    location="India",
    skills="Python, SQL, Machine Learning",
    level="Internship"
)

print("Fresh search results:", len(live_results))

for job in live_results[:5]:
    print("\nTitle:", job.get("title"))
    print("URL:", job.get("url"))

Fresh search results: 10

Title: Machine Learning Internships - 151 Intern Jobs in Oct 2026
URL: https://internshala.com/internships/machine-learning-internship/

Title: 182 Machine Learning With Python Internship Jobs in India
URL: https://in.linkedin.com/jobs/machine-learning-with-python-internship-jobs

Title: 160 machine learning intern jobs in India, October 2026
URL: https://www.glassdoor.co.in/Job/india-machine-learning-intern-jobs-SRCH_IL.0,5_IN115_KO6,29.htm

Title: 500 Python Machine Learning Internship Job Vacancies
URL: https://in.indeed.com/q-python-machine-learning-internship-jobs.html

Title: 901 Machine Learning Intern Job Vacancies In India
URL: https://www.naukri.com/machine-learning-intern-jobs-in-india

In [28]:
# Step 21: Live Search → Fetch pipeline

import os
from tinyfish import TinyFish

os.environ["TINYFISH_API_KEY"] = API_KEY
client = TinyFish()

# Select up to 10 unique URLs from the latest search
seen_urls = set()
urls_to_fetch = []

for item in live_results:
    url = item.get("url", "").strip()

    if url and url not in seen_urls:
        seen_urls.add(url)
        urls_to_fetch.append(url)

    if len(urls_to_fetch) == 10:
        break

print("Fetching", len(urls_to_fetch), "pages...")

live_fetch = client.fetch.get_contents(
    urls=urls_to_fetch,
    format="markdown",
    ttl=0,
    purpose=(
        "Identify specific AI, machine learning, and data science "
        "job or internship vacancies. Extract job title, company, "
        "location, requirements, and direct application URL."
    )
)

# Show compact output rather than entire webpages
print("\nSuccessfully fetched:", len(live_fetch.results))
print("Failed URLs:", len(live_fetch.errors))

for page in live_fetch.results:
    text = page.text or ""

    print("\n" + "-" * 55)
    print("Page:", page.title)
    print("URL:", page.url)

    # Show only a short preview
    lines = [line.strip() for line in text.splitlines() if line.strip()]
    for line in lines[:6]:
        print(line[:180])

Fetching 10 pages...

Successfully fetched: 9
Failed URLs: 1

-------------------------------------------------------
Page: Machine Learning Internships - 144 Intern Jobs in Oct 2026
URL: https://internshala.com/internships/machine-learning-internship/
## Machine Learning Internship Snapshot
Looking for Machine Learning internships? Currently, there are 144 active Machine Learning internship vacancies from 130 companies across key sector(s) such as IT/Technology, Educa
### Machine Learning Internship Types and Stipend Insights
Internshala offers a variety of Machine Learning internship opportunities to match different work preferences:
* 118 full-time Machine Learning internships
* 66 part-time Machine Learning internships

-------------------------------------------------------
Page: وظائف ‏Machine Learning With Python Internship‏ في ‏الهند‏ (‏320‏ من الوظائف المتاحة)‏ | LinkedIn
URL: https://in.linkedin.com/jobs/machine-learning-with-python-internship-jobs
احصل على إشعارات عندما يتم نشر وظيفة جديدة.
تعيين تنبيه
# ٣٢٠ Machine Learning With Python Internship وظائف في الهند
* Data Science Intern
### Data Science Intern
#### Sony Research India

-------------------------------------------------------
Page: 500 Python Machine Learning Internship Job Vacancies | Indeed
URL: https://in.indeed.com/q-python-machine-learning-internship-jobs.html
Upload your CV and find your next job on Indeed!
&nbsp;
# python machine learning internship jobs
Sort by:  -
* |  |
| --- |

-------------------------------------------------------
Page: None
URL: https://www.naukri.com/machine-learning-intern-jobs-in-india
## Application error: a client-side exception has occurred (see the browser console for more information).

-------------------------------------------------------
Page: Machine Learning Internships in India
URL: https://in.prosple.com/machine-learning-internships-india
I'm studying
Location
India
Remote
New
Job type

-------------------------------------------------------
Page: Artificial Intelligence (AI) Internships - 215 Intern Jobs in Oct 2026
URL: https://internshala.com/internships/artificial-intelligence-ai-internship/
## Artificial Intelligence (AI) Internship Snapshot
Looking for Artificial Intelligence (AI) internships? Currently, there are 215 active Artificial Intelligence (AI) internship vacancies from 217 companies across key sector(s) such
### Artificial Intelligence (AI) Internship Types and Stipend Insights
Internshala offers a variety of Artificial Intelligence (AI) internship opportunities to match different work preferences:
* 199 full-time Artificial Intelligence (AI) internships
* 90 part-time Artificial Intelligence (AI) internships

-------------------------------------------------------
Page: Skill India Digital Hub (SIDH) - Upskilling, reskilling, career growth and lifelong learning
URL: https://www.skillindiadigital.gov.in/internship/detail/48
Data Science with Python Internship - Internship By Henry Harvin
# Data Science with Python Internship
* Henry Harvin
* FREE
* IT-ITeS
* 1 Month

-------------------------------------------------------
Page: وظائف ‏Machine Learning Intern‏ في ‏الهند‏ (‏323‏ من الوظائف المتاحة)‏ | LinkedIn
URL: https://in.linkedin.com/jobs/machine-learning-intern-jobs
احصل على إشعارات عندما يتم نشر وظيفة جديدة.
تعيين تنبيه
# ٣٢٣ Machine Learning Intern وظائف في الهند
* Machine Learning Intern
### Machine Learning Intern
#### ERIC Robotics

-------------------------------------------------------
Page: Python Machine Learning Internship & Full Stack Developer Training in Pune | Anvistar ITS Pvt. Ltd.
URL: https://www.anvistar.in/python-ml-internship.html
Loading...
## Best Python Machine Learning Course in Pune with 100% Placement Assistance
Join our top-rated **Python Machine Learning Program in Pune** and gain hands-on experience in Python, Data Science, Machine Learning, AI, Pandas, NumPy, Matplotlib, Scikit-learn,
* Practical Python Machine Learning Internship with Live Projects
* Internship for Freshers and Final Year Students in Python & ML
* Learn Python, Pandas, NumPy, Scikit-learn, TensorFlow, AI Tools

In [22]:
import re
from urllib.parse import urlparse

def is_job_listing(page):
    url = page.url.lower()
    text = (page.text or "").lower()
    title = (page.title or "").lower()

    # Common individual job-page patterns
    individual_patterns = [
        "jobs.lever.co/",
        "boards.greenhouse.io/",
        "job-boards.greenhouse.io/",
        "jobs.ashbyhq.com/"
    ]

    if any(pattern in url for pattern in individual_patterns):
        return True

    # Look for evidence of an individual role
    role_terms = [
        "job description", "responsibilities",
        "qualifications", "requirements",
        "apply for this job", "apply now"
    ]

    evidence_count = sum(term in text for term in role_terms)

    # Exclude obvious search/category pages
    broad_terms = [
        "internships in india", "jobs in india",
        "job vacancies", "internship snapshot",
        "search results"
    ]

    if any(term in title for term in broad_terms):
        return False

    return evidence_count >= 3

individual_pages = [
    page for page in live_fetch.results
    if is_job_listing(page)
]

print("Fetched pages:", len(live_fetch.results))
print("Potential individual listings:", len(individual_pages))

for page in individual_pages:
    print("\n", page.title)
    print(page.url)

Fetched pages: 7
Potential individual listings: 0

In [27]:
import pandas as pd
from urllib.parse import urlparse

fetched_by_url = {
    page.url.rstrip("/"): page
    for page in live_fetch.results
}

final_rows = []
seen = set()

for item in live_results:
    url = item.get("url", "").strip()
    title = item.get("title", "").strip()

    if not url or not title or url.rstrip("/") in seen:
        continue

    seen.add(url.rstrip("/"))

    page = fetched_by_url.get(url.rstrip("/"))
    text = (page.text if page else item.get("snippet", "")) or ""
    combined = (title + " " + text).lower()

    score = sum(
        term in combined
        for term in ["machine learning", "artificial intelligence",
                     "python", "data science", "intern"]
    )

    final_rows.append({
        "Job / Page Title": title,
        "Source": urlparse(url).netloc,
        "Match Score": round(score / 5 * 100),
        "Fetch Status": "Fetched" if page else "Search result only",
        "Apply / Source Link": url
    })

final_df = pd.DataFrame(final_rows)

if not final_df.empty:
    final_df = final_df.sort_values("Match Score", ascending=False)

print("Live results:", len(final_df))
display(final_df)

Live results: 10

,Job / Page Title,Source,Match Score,Fetch Status,Apply / Source Link
1,182 Machine Learning With Python Internship Jo...,in.linkedin.com,100,Fetched,https://in.linkedin.com/jobs/machine-learning-...
3,500 Python Machine Learning Internship Job Vac...,in.indeed.com,100,Search result only,https://in.indeed.com/q-python-machine-learnin...
8,315 Machine Learning Intern jobs in India,in.linkedin.com,100,Fetched,https://in.linkedin.com/jobs/machine-learning-...
9,Best Python Machine Learning Course in Pune ...,www.anvistar.in,100,Fetched,https://www.anvistar.in/python-ml-internship.html
6,Artificial Intelligence (AI) Internships - 215...,internshala.com,100,Fetched,https://internshala.com/internships/artificial...
0,Machine Learning Internships - 151 Intern Jobs...,internshala.com,80,Fetched,https://internshala.com/internships/machine-le...
2,"160 machine learning intern jobs in India, Oct...",www.glassdoor.co.in,80,Fetched,https://www.glassdoor.co.in/Job/india-machine-...
7,Data Science with Python Internship,www.skillindiadigital.gov.in,60,Search result only,https://www.skillindiadigital.gov.in/internshi...
5,Machine Learning Internships in India (297 ope...,in.prosple.com,40,Search result only,https://in.prosple.com/machine-learning-intern...
4,901 Machine Learning Intern Job Vacancies In I...,www.naukri.com,40,Fetched,https://www.naukri.com/machine-learning-intern...

In [24]:
import os
from tinyfish import TinyFish

# Reuse the API key already loaded in Colab
os.environ["TINYFISH_API_KEY"] = API_KEY
client = TinyFish()

# Pick a real career page from your existing search results
agent_url = "https://jobs.lever.co/Sprinto"

goal = """
Find AI, machine learning, data science, or software engineering
internship openings on this company's careers website.

Navigate the website as needed. Extract up to 5 individual openings.
For each opening, return:
- job_title
- company
- location
- job_type
- application_url

Return only structured JSON. Do not invent missing details.
If no suitable openings are found, return an empty list.
"""

with client.agent.stream(url=agent_url, goal=goal) as stream:
    for event in stream:
        print(event)

type=<EventType.STARTED: 'STARTED'> run_id='5dc1c695-8313-4230-953f-404ae395e822' timestamp=datetime.datetime(2026, 10, 15, 5, 55, 55, 170000, tzinfo=TzInfo(0))
type=<EventType.STREAMING_URL: 'STREAMING_URL'> run_id='5dc1c695-8313-4230-953f-404ae395e822' streaming_url='https://ip-54-183-170-255.tetra-data.production.tinyfish.io/tf-9a5d2c38-7b6a-4606-9acc-64dd7951e5cd/stream/0' timestamp=datetime.datetime(2026, 10, 15, 5, 55, 56, 817000, tzinfo=TzInfo(0))
type=<EventType.PROGRESS: 'PROGRESS'> run_id='5dc1c695-8313-4230-953f-404ae395e822' purpose='Navigate to Sprinto careers page to find internship openings' timestamp=datetime.datetime(2026, 10, 15, 5, 55, 58, 183000, tzinfo=TzInfo(0))
type=<EventType.PROGRESS: 'PROGRESS'> run_id='5dc1c695-8313-4230-953f-404ae395e822' purpose='Extract all job openings with details from careers page' timestamp=datetime.datetime(2026, 10, 15, 5, 56, 2, 255000, tzinfo=TzInfo(0))
type=<EventType.PROGRESS: 'PROGRESS'> run_id='5dc1c695-8313-4230-953f-404ae395e822' purpose='Identify internship positions specifically' timestamp=datetime.datetime(2026, 10, 15, 5, 56, 7, 513000, tzinfo=TzInfo(0))
type=<EventType.PROGRESS: 'PROGRESS'> run_id='5dc1c695-8313-4230-953f-404ae395e822' purpose='Check AI Implementation Intern job details' timestamp=datetime.datetime(2026, 10, 15, 5, 56, 12, 880000, tzinfo=TzInfo(0))
type=<EventType.PROGRESS: 'PROGRESS'> run_id='5dc1c695-8313-4230-953f-404ae395e822' purpose='Extract full details of AI Implementation Intern' timestamp=datetime.datetime(2026, 10, 15, 5, 56, 16, 5000, tzinfo=TzInfo(0))
type=<EventType.PROGRESS: 'PROGRESS'> run_id='5dc1c695-8313-4230-953f-404ae395e822' purpose='Check Finance Intern details' timestamp=datetime.datetime(2026, 10, 15, 5, 56, 19, 334000, tzinfo=TzInfo(0))
type=<EventType.PROGRESS: 'PROGRESS'> run_id='5dc1c695-8313-4230-953f-404ae395e822' purpose='Return to main careers page to gather all internship details' timestamp=datetime.datetime(2026, 10, 15, 5, 56, 22, 30000, tzinfo=TzInfo(0))
type=<EventType.PROGRESS: 'PROGRESS'> run_id='5dc1c695-8313-4230-953f-404ae395e822' purpose='Return internship openings found on Sprinto careers page' timestamp=datetime.datetime(2026, 10, 15, 5, 56, 29, 841000, tzinfo=TzInfo(0))
type=<EventType.COMPLETE: 'COMPLETE'> run_id='5dc1c695-8313-4230-953f-404ae395e822' status=<RunStatus.COMPLETED: 'COMPLETED'> timestamp=datetime.datetime(2026, 10, 15, 5, 56, 32, 583000, tzinfo=TzInfo(0)) result_json={'result': [{'job_title': 'AI Implementation Intern', 'company': 'Sprinto', 'location': 'Bengaluru', 'job_type': 'Remote', 'application_url': 'https://jobs.lever.co/Sprinto/6dfd5f41-57b6-40e8-9eab-ba4083c1a7c4'}, {'job_title': 'Information Security Compliance Intern', 'company': 'Sprinto', 'location': 'Remote (India)', 'job_type': 'Remote', 'application_url': 'https://jobs.lever.co/Sprinto/b0f52d4a-c9ac-414d-86c9-2f2f35868aef'}, {'job_title': 'Talent Acquisition Intern', 'company': 'Sprinto', 'location': 'Bengaluru', 'job_type': 'Remote', 'application_url': 'https://jobs.lever.co/Sprinto/24691575-e46e-4d9f-a07a-137d1d84ea55'}, {'job_title': 'MRE Intern', 'company': 'Sprinto', 'location': 'Bengaluru', 'job_type': 'Remote', 'application_url': 'https://jobs.lever.co/Sprinto/47036e01-4a27-4380-bcf1-83f158febe95'}, {'job_title': 'Revenue & Operations Intern', 'company': 'Sprinto', 'location': 'Bengaluru', 'job_type': 'Remote', 'application_url': 'https://jobs.lever.co/Sprinto/856517f8-cc53-4d48-a5aa-137734e61489'}]} error=None

In [25]:
# Display the final Agent event
print(event)

type=<EventType.COMPLETE: 'COMPLETE'> run_id='5dc1c695-8313-4230-953f-404ae395e822' status=<RunStatus.COMPLETED: 'COMPLETED'> timestamp=datetime.datetime(2026, 10, 15, 5, 56, 32, 583000, tzinfo=TzInfo(0)) result_json={'result': [{'job_title': 'AI Implementation Intern', 'company': 'Sprinto', 'location': 'Bengaluru', 'job_type': 'Remote', 'application_url': 'https://jobs.lever.co/Sprinto/6dfd5f41-57b6-40e8-9eab-ba4083c1a7c4'}, {'job_title': 'Information Security Compliance Intern', 'company': 'Sprinto', 'location': 'Remote (India)', 'job_type': 'Remote', 'application_url': 'https://jobs.lever.co/Sprinto/b0f52d4a-c9ac-414d-86c9-2f2f35868aef'}, {'job_title': 'Talent Acquisition Intern', 'company': 'Sprinto', 'location': 'Bengaluru', 'job_type': 'Remote', 'application_url': 'https://jobs.lever.co/Sprinto/24691575-e46e-4d9f-a07a-137d1d84ea55'}, {'job_title': 'MRE Intern', 'company': 'Sprinto', 'location': 'Bengaluru', 'job_type': 'Remote', 'application_url': 'https://jobs.lever.co/Sprinto/47036e01-4a27-4380-bcf1-83f158febe95'}, {'job_title': 'Revenue & Operations Intern', 'company': 'Sprinto', 'location': 'Bengaluru', 'job_type': 'Remote', 'application_url': 'https://jobs.lever.co/Sprinto/856517f8-cc53-4d48-a5aa-137734e61489'}]} error=None

In [30]:
agent_events = []

with client.agent.stream(url=agent_url, goal=goal) as stream:
    for event in stream:
        agent_events.append(event)
        print(event.type)

# Inspect the final event's available fields
final_event = agent_events[-1]

print("\nFinal event details:")
print(final_event.model_dump() if hasattr(final_event, "model_dump")
      else vars(final_event))

STARTED
STREAMING_URL
PROGRESS
PROGRESS
PROGRESS
PROGRESS
PROGRESS
PROGRESS
PROGRESS
PROGRESS
HEARTBEAT
COMPLETE

Final event details:
{'type': <EventType.COMPLETE: 'COMPLETE'>, 'run_id': 'dae1e1d8-0cdf-4f3e-9395-d259b7c1663a', 'status': <RunStatus.COMPLETED: 'COMPLETED'>, 'timestamp': datetime.datetime(2026, 10, 15, 6, 10, 29, 469000, tzinfo=TzInfo(0)), 'result_json': {'result': [{'job_title': 'AI Implementation Intern', 'company': 'Sprinto', 'location': 'Bengaluru', 'job_type': 'Remote', 'application_url': 'https://jobs.lever.co/Sprinto/6dfd5f41-57b6-40e8-9eab-ba4083c1a7c4'}, {'job_title': 'Revenue & Operations Intern', 'company': 'Sprinto', 'location': 'Bengaluru', 'job_type': 'Remote', 'application_url': 'https://jobs.lever.co/Sprinto/856517f8-cc53-4d48-a5aa-137734e61489'}]}, 'error': None}

In [32]:

from IPython.display import display, HTML
from urllib.parse import urlparse
from html import escape
import re

# Use the live results already collected
pages = {
    p.url.rstrip("/"): p for p in live_fetch.results
}

cards = []

for job in live_results:
    title = (job.get("title") or "Untitled opportunity").strip()
    url = (job.get("url") or "").strip()
    snippet = (job.get("snippet") or "").strip()

    if not url.startswith(("https://", "http://")):
        continue

    page = pages.get(url.rstrip("/"))
    description = snippet or (
        re.sub(r"\s+", " ", page.text)[:300]
        if page and page.text else
        "Open the source page to explore this opportunity."
    )

    domain = urlparse(url).netloc.removeprefix("www.")
    text_to_match = (title + " " + description).lower()

    keywords = [
        "artificial intelligence", "machine learning",
        "data science", "python", "intern"
    ]
    matches = sum(k in text_to_match for k in keywords)
    score = round(matches / len(keywords) * 100)

    cards.append({
        "title": title,
        "url": url,
        "domain": domain,
        "description": description,
        "score": score,
        "fetched": page is not None
    })

# Remove duplicate URLs and sort by keyword relevance
unique = {}
for card in cards:
    unique.setdefault(card["url"].rstrip("/"), card)

cards = sorted(
    unique.values(),
    key=lambda x: x["score"],
    reverse=True
)[:10]

card_html = ""

for job in cards:
    title = escape(job["title"])
    domain = escape(job["domain"])
    description = escape(job["description"][:280])
    url = escape(job["url"], quote=True)
    score = job["score"]
    status = "Page fetched" if job["fetched"] else "Search result"
    status_color = "#047857" if job["fetched"] else "#64748b"

    card_html += f"""
    <div style="background:#fff;border:1px solid #e2e8f0;
        border-radius:16px;padding:20px;margin:12px 0;
        box-shadow:0 3px 12px rgba(15,23,42,.05);
        font-family:Arial,sans-serif;color:#172033;">

      <div style="display:flex;justify-content:space-between;
          gap:12px;align-items:flex-start;flex-wrap:wrap;">

        <div style="flex:1;min-width:200px;">
          <div style="font-size:12px;color:#64748b;
              margin-bottom:8px;">{domain}</div>
          <div style="font-size:18px;font-weight:700;
              line-height:1.4;">{title}</div>
        </div>

        <div style="background:#ecfdf5;color:#047857;
            padding:7px 10px;border-radius:10px;
            font-size:12px;font-weight:700;">
          {score}% keyword relevance
        </div>
      </div>

      <p style="font-size:14px;color:#475569;
          line-height:1.7;margin:14px 0;">
          {description}
        </p>

      <div style="display:flex;justify-content:space-between;
          align-items:center;gap:12px;flex-wrap:wrap;">

        <span style="font-size:12px;color:{status_color};">
          ● {status}
        </span>

        <a href="{url}" target="_blank"
           style="display:inline-block;background:#4f46e5;
           color:white;text-decoration:none;padding:10px 16px;
           border-radius:9px;font-weight:700;font-size:13px;">
          View opportunity ↗
        </a>
      </div>
    </div>
    """

if not cards:
    card_html = """
    <p>No results available. Run the TinyFish Search cell first.</p>
    """

display(HTML(f"""
<div style="font-family:Arial,sans-serif;background:#f8fafc;
    padding:24px;border-radius:20px;color:#172033;">

  <div style="background:linear-gradient(120deg,#312e81,#6366f1);
      color:white;padding:28px;border-radius:18px;margin-bottom:20px;">

    <div style="font-size:12px;letter-spacing:2px;
        font-weight:700;opacity:.85;">TINYFISH × TECHNОJAM</div>

    <h1 style="font-size:30px;margin:12px 0 8px;">
      🚀 ApplyPilot AI
    </h1>

    <p style="font-size:15px;line-height:1.6;margin:0;">
      Discover opportunities. Explore careers. Find your next move.
    </p>
  </div>

  <div style="display:flex;gap:12px;flex-wrap:wrap;margin-bottom:20px;">
    <div style="flex:1;min-width:110px;background:white;
        padding:16px;border-radius:12px;border:1px solid #e2e8f0;">
      <div style="font-size:25px;font-weight:800;">{len(cards)}</div>
      <div style="font-size:12px;color:#64748b;">Unique results</div>
    </div>

    <div style="flex:1;min-width:110px;background:white;
        padding:16px;border-radius:12px;border:1px solid #e2e8f0;">
      <div style="font-size:25px;font-weight:800;">
        {sum(c["fetched"] for c in cards)}
      </div>
      <div style="font-size:12px;color:#64748b;">Pages fetched</div>
    </div>

    <div style="flex:1;min-width:110px;background:white;
        padding:16px;border-radius:12px;border:1px solid #e2e8f0;">
      <div style="font-size:25px;font-weight:800;">Live</div>
      <div style="font-size:12px;color:#64748b;">Search source</div>
    </div>
  </div>

  <h2 style="font-size:21px;margin:22px 0 6px;">
    Opportunities for you
  </h2>
  <p style="font-size:13px;color:#64748b;margin-bottom:16px;">
    Ranked using keyword relevance from your existing live search results.
  </p>

  {card_html}

  <p style="font-size:12px;line-height:1.6;color:#64748b;
      margin-top:20px;">
    Note: Relevance scores are simple keyword scores, not AI confidence.
    Results may be job-board pages rather than individual vacancies.
    Verify availability, eligibility, location and application details
    on the source website before applying.
  </p>
</div>
"""))

In [33]:

import requests
import pandas as pd

query = """
UI UX Designer internships and entry-level jobs in Delhi India,
UI designer, UX designer, product design intern apply
"""

response = requests.get(
    "https://api.search.tinyfish.ai",
    headers={"X-API-Key": API_KEY},
    params={
        "query": query,
        "location": "IN",
        "language": "en"
    },
    timeout=60
)

response.raise_for_status()
uiux_results = response.json().get("results", [])

uiux_df = pd.DataFrame([
    {
        "Job / Page Title": item.get("title", ""),
        "Website": item.get("site_name", ""),
        "URL": item.get("url", ""),
        "Description": item.get("snippet", "")
    }
    for item in uiux_results
])

uiux_df = uiux_df.drop_duplicates(subset=["URL"])

print("UI/UX search results:", len(uiux_df))
display(uiux_df)

UI/UX search results: 10

,Job / Page Title,Website,URL,Description
0,UI/UX Internships in Delhi - 88 Intern Jobs in...,internshala.com,https://internshala.com/internships/ui-ux-inte...,Find UI/UX internships in Delhi. Apply for 88 ...
1,Ux Intern Jobs in Greater Delhi Area (54 Open ...,in.linkedin.com,https://in.linkedin.com/jobs/ux-intern-jobs-gr...,54 Ux Intern jobs in Greater Delhi Area. New U...
2,75 Ui Ux Design Internship Job Vacancies,in.indeed.com,https://in.indeed.com/q-ui-ux-design-internshi...,This is a remote internship opportunity suitab...
3,"11 ux designer internship jobs in Delhi, Septe...",www.glassdoor.co.in,https://www.glassdoor.co.in/Job/delhi-ux-desig...,11 Ux designer internship jobs in Delhi ; Mant...
4,UI UX Design Internships in India (317 open now!),in.prosple.com,https://in.prosple.com/ui-ux-design-internship...,Find open UI UX Design Internships in India fr...
5,Product Design Jobs in India,nextleap.app,https://nextleap.app/jobs/ui-ux-design,Find top product design jobs in India. Apply t...
6,142 Ux Internship Job Vacancies In Delhi Ncr,www.naukri.com,https://www.naukri.com/ux-internship-jobs-in-d...,Explore Latest Ux Internship Job Vacancies In ...
7,"Ui Ux Design Internship jobs in Laxmi Nagar, D...",in.indeed.com,https://in.indeed.com/q-ui-ux-design-internshi...,5 Ui Ux Design Internship jobs available in La...
8,104 Ui Ux Design Internship jobs in India,in.linkedin.com,https://in.linkedin.com/jobs/ui-ux-design-inte...,UI/UX Design Intern | Entry Level | Fresher | ...
9,UI / UX Design Intern jobs in Delhi,www.instahyre.com,https://www.instahyre.com/ui-ux-design-intern-...,Apply to 365 UI / UX Design Intern jobs in Del...